using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using RenderHeads.Media.AVProVideo;

public class PlayResponse7 : MonoBehaviour
{
   // public float timeToStop = 3f;

    [SerializeField]
    private MediaPlayer mediaPlayer7;

    private void Awake()
    {
        HUDSingleton.Instance.gameObject.SetActive(false);


      //  Inventory.Instance.gameObject.SetActive(false);

        GameObject.Find("tempMainCamera7").SetActive(true);
        CameraMain.Instance.gameObject.SetActive(false);
    }





   /*
    private void Start()
    {
        Destroy(mediaPlayer7, timeToStop);

        Destroy(GameObject.Find("screen7"), timeToStop);
        Destroy(GameObject.Find("DL7"), timeToStop);

    }
*/
    private void Update()
    {
        if (mediaPlayer7 == null)
        {
            HUDSingleton.Instance.gameObject.SetActive(true);

           // Inventory.Instance.gameObject.SetActive(true);


            CameraMain.Instance.gameObject.SetActive(true);
            GameObject.Find("tempMainCamera7").SetActive(false);
        }

    }

}
    
